// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSnXaYx7evHI1fK2z90A7CoWBXzfxZJU',
    appId: '1:222167360217:web:f9f933053c4a0c742ed4c8',
    messagingSenderId: '222167360217',
    projectId: 'ecommerceflutter-47dfb',
    authDomain: 'ecommerceflutter-47dfb.firebaseapp.com',
    storageBucket: 'ecommerceflutter-47dfb.appspot.com',
    measurementId: 'G-3DLRFKE38L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpP9motUcR1q4QGiHYyCUeZdw7_lwMio4',
    appId: '1:222167360217:android:b190dab9c4c755cd2ed4c8',
    messagingSenderId: '222167360217',
    projectId: 'ecommerceflutter-47dfb',
    storageBucket: 'ecommerceflutter-47dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-S4sjDLktzJB0DUP4E8suld1lquV77eg',
    appId: '1:222167360217:ios:1a1475b1315640e42ed4c8',
    messagingSenderId: '222167360217',
    projectId: 'ecommerceflutter-47dfb',
    storageBucket: 'ecommerceflutter-47dfb.appspot.com',
    androidClientId: '222167360217-kukmn7ekqki83988hpl582qltkm4k7bv.apps.googleusercontent.com',
    iosClientId: '222167360217-0jke1n3jc5cmpgfikuum9umb8bdc0i9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeMusician',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-S4sjDLktzJB0DUP4E8suld1lquV77eg',
    appId: '1:222167360217:ios:1a1475b1315640e42ed4c8',
    messagingSenderId: '222167360217',
    projectId: 'ecommerceflutter-47dfb',
    storageBucket: 'ecommerceflutter-47dfb.appspot.com',
    androidClientId: '222167360217-kukmn7ekqki83988hpl582qltkm4k7bv.apps.googleusercontent.com',
    iosClientId: '222167360217-0jke1n3jc5cmpgfikuum9umb8bdc0i9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.makeMusician',
  );
}
